#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel as ConsoleKernel;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$app->handleCommand(
    $app->make(ConsoleKernel::class),
    $argv
);
